export enum JOB_SERVICE_MESSAGE_PATTERNS {
  CREATE_JOB = 'CREATE_JOB',
  GET_JOBS = 'GET_JOBS',
  GET_JOB_CHANGELOG = 'GET_JOB_CHANGELOG',
}

export enum DATA_CONFIG_TYPES {
  STATIC_TEXT = 'staticText',
  IMAGE = 'image',
  FROM_DATASET = 'fromDataset',
}
